# DFS 03
graphs = {
    '1': ['2','3'],
    '2': ['5','6'],
    '3': ['7','4'],
    '4': [],
    '5': [],
    '6': [],
    '7': ['8'],
    '8': []
}
def bfs(start):
    visited = []     
    queue = []       

    visited.append(start)
    queue.append(start)

    while queue:
        node = queue.pop(0)
        print(node, end=" ")

        for neighbour in graphs[node]:
            if neighbour not in visited:
                visited.append(neighbour)
                queue.append(neighbour)
bfs('1')
